template_project/template_app/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
	path('', views.login_index, name="login"),
	path('logout', views.logout_index, name="logout"),
	path('registrarse', views.registrarse, name="register"),
	path('home', views.template_view, name="home"),
	path('crearPost', views.crearPost, name="crearPost"),
	path('verNoticias', views.verNoticias, name="verNoticias"),
	path('buscarUsuarios', views.buscarUsuarios, name="buscarUsuarios"),
	path('notificaciones', views.notificaciones, name="notificaciones"),
    #path('', views.VistaPrecioDolar.as_view(template_name ='index.html'), name = 'vistapreciodolar'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('template_app.urls')),
]

template_project/template_app/models.py
from django.db import models

# Create your models here.

class Mensaje(models.Model):

	mensaje = models.CharField(max_length=240)

	class Meta():
		db_table = 'mensajes'
		
	'''
	def __str__(self):
		return str(self.attr1) + ' - ' + str(self.attr2)
	'''


class Post(models.Model):

	autor = models.CharField(max_length=100, default="Anonymous")
	titulo = models.CharField(max_length=100)
	imagen = models.FileField(upload_to='template_project/static/uploads/')
	text = models.CharField(max_length=240)

	class Meta():
		db_table = 'posts'
		
	'''
	def __str__(self):
		return str(self.attr1) + ' - ' + str(self.attr2)

	'''


class Seguidos(models.Model):

	seguidor = models.CharField(max_length=100)
	seguido = models.CharField(max_length=100)

	class Meta():
		db_table = 'seguidos'
		
	'''
	def __str__(self):
		return str(self.attr1) + ' - ' + str(self.attr2)
	'''


class Likes(models.Model):

	idPost = models.CharField(max_length=100)
	seguidor = models.CharField(max_length=100)

	class Meta():
		db_table = 'likes'
		
	'''
	def __str__(self):
		return str(self.attr1) + ' - ' + str(self.attr2)
	'''

template_project/template_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from . import models


class RegisterForm(UserCreationForm):
	username = forms.CharField(label='Usuario', widget = forms.TextInput(attrs={'placeholder':'Usuario'}), required = True)
	first_name = forms.CharField(label='Usuario', widget = forms.TextInput(attrs={'placeholder':'Nombre de Pila'}), required = True)
	password1 = forms.CharField(label='Password 1', help_text='La contraseña debe contener mas de 8 caracteres alfanumericos', widget=forms.PasswordInput(attrs={'placeholder':'Password 1'}), required = True)
	password2 = forms.CharField(label='Password 2', widget=forms.PasswordInput(attrs={'placeholder':'Password 2'}), required = True)


class LoginForm(forms.Form):
	username = forms.CharField(label='Usuario', widget = forms.TextInput(attrs={'placeholder':'Usuario'}), required = True)
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder':'Password'}), required = True)

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'password1', 'password2']

#class ModelForm(ModelForm):
#	class Meta:
#		model = models.model_name
#		fields = '__all__'
#		widgets = {
#			'username' : forms.TextInput(attrs = {'placeholder': 'Username'}),
#			'email' : forms.TextInput(attrs = {'placeholder': 'E-Mail'}),
#			'password': forms.PasswordInput(attrs = {'placeholder': 'Password'}), 
#			'password2': forms.PasswordInput(attrs = {'placeholder': 'Password repeat'}), 
#		}

#class NameForm(forms.Form):
#	field_name = forms.CharField(label='', widget = forms.TextInput(attrs={'placeholder':'Mensaje a Enviar'}), required = True)
	


class MessageForm(forms.Form):
	mensaje = forms.CharField(label='', widget = forms.TextInput(attrs={'placeholder':'Mensaje a Enviar'}), required = True)
	

class CargarPost(forms.Form):
	titulo = forms.CharField(label='Titulo', widget = forms.TextInput(attrs={'placeholder':'Titulo del Post'}), required = True)
	imagen = forms.FileField(label='Ingrese una imagen', required = False)
	texto = forms.CharField(label='Texto', widget = forms.Textarea(attrs={'placeholder':'Texto del Post'}), required = True)
	


class BuscarUsrForm(forms.Form):
	mensaje = forms.ModelChoiceField(queryset=User.objects.all())


class ObtenerPost(forms.Form):
	autor = forms.CharField(widget = forms.HiddenInput(), required = True)
	titulo = forms.CharField(widget = forms.HiddenInput(), required = True)
	texto = forms.CharField(widget = forms.HiddenInput(), required = True)
	

template_project/template_app/views.py
from django.shortcuts import render , redirect

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User

from . import forms

from . import models

from .consumer import notifiSeguim_lst_msg, notifiLikes_lst_msg, noticias_lst_msg
from .producer import msg_seguir_usuario, msg_like_post, msg_crear_post
from .newtopic import crear_topic_seguidores


def login_index(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
	# if this is a POST request we need to process the form data
		if request.method == 'POST':
			# create a form instance and populate it with data from the request:
			form = forms.LoginForm(request.POST)
			# check whether it's valid:
			if form.is_valid():
				
				username = request.POST['username']
				password = request.POST['password']
				
				user = authenticate(request, username=username, password=password)

				if user is not None:
						if user.is_active:				
							login(request, user)
							return redirect('home')
							messages.success(request,'Te has identificado correctamente.')
						else:
							messages.error(request,'Tu usuario no esta activo.')
				else:
					messages.error(request,'Usuario y/o contraseña incorrectas.')

				form = forms.LoginForm()
				context = {'form': form}
		else:

			form = forms.LoginForm()
			context = {'form': form}

	return render(request, 'index.html', context)


def logout_index(request):
	logout(request)
	return redirect('login')


def registrarse(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form = forms.RegisterForm()
		if request.method == 'POST':
			form = forms.RegisterForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request,'Te has registrado con exito '+ user)
				msg = crear_topic_seguidores(user)
				print(msg)
				return redirect('login')
			else:
				messages.error(request,'Error al registrarte')

	context = {'form':form}

	return render(request, 'register.html', context)


@login_required(login_url='login')
def template_view(request):

	item_list = []

	context = {'item_list': item_list}

	return render(request, 'home.html', context)


@login_required(login_url='login')
def crearPost(request):

	item_list = []
	form_post = forms.CargarPost(request.POST, request.FILES) 

	if form_post.is_valid():
		titulo = form_post.cleaned_data['titulo']
		texto = form_post.cleaned_data['texto']
		autor = str(request.user)

		for f in request.FILES.getlist('imagen'): 
			models.Post.objects.create(autor= autor, titulo=titulo, imagen=f, text = texto)
		messages.success(request,'Post creado correctamente ')

		post = models.Post.objects.filter(autor= autor, titulo=titulo, text = texto)

		for p in post:
			idPost = p.id

		lst_topics = []

		lst_seguidores = models.Seguidos.objects.filter(seguido= autor)

		for item in lst_seguidores:
			lst_topics.append(item.seguidor+"_News")

		msg = msg_crear_post(str(idPost), lst_topics)
		print(msg)


		form_post = forms.CargarPost()
	else:
		item_list = []
		form_post = forms.CargarPost()

	context = {'item_list': item_list, 'form_post': form_post}

	return render(request, 'cargaPost.html', context)


@login_required(login_url='login')
def verNoticias(request):

	item_list = []
	lst_msg_generator_idPost_aux = []
	lst_msg_generator_idPost = []
	generator_idPost = noticias_lst_msg(str(request.user))

	for item in generator_idPost:				# EXTRAE CADA MJE DEL TOPIC Y LO GUARDA EN UNA LISTA
		for i in item:
			lst_msg_generator_idPost_aux.append(i)				
		
	for item in lst_msg_generator_idPost_aux[::-1]:			#INVIERTE EL ORDEN DE LA LISTA PARA QUE EL MJE MAS RECIENTE ESTE PRIMERO
		lst_msg_generator_idPost.append(item)
	print (lst_msg_generator_idPost)

	for item in lst_msg_generator_idPost:
		post = models.Post.objects.filter(id = int(item))

		for item in post: 
			item_list.append(item)

	form_msg = forms.ObtenerPost();
	
	if request.method == 'POST':
		form_msg = forms.ObtenerPost(request.POST)
		if form_msg.is_valid():
			autor = form_msg.cleaned_data['autor']
			titulo = form_msg.cleaned_data['titulo']
			texto = form_msg.cleaned_data['texto']
			post_lst = models.Post.objects.get(autor= autor, titulo=titulo, text = texto)
			
			models.Likes.objects.create(idPost= post_lst.id, seguidor=autor)
			msg = msg_like_post(str(request.user), post_lst.autor, post_lst.titulo)		# LLAMA A PRODUCER.PY
			print (msg)

		else:
			form_msg = forms.ObtenerPost()
	else:
		form_msg = forms.ObtenerPost()

	context = {'item_list': item_list, 'form_msg': form_msg}

	return render(request, 'verNoticias.html', context)



@login_required(login_url='login')
def buscarUsuarios(request):

	form_msg= forms.BuscarUsrForm()

	if request.method == 'POST':
		form_msg = forms.BuscarUsrForm(request.POST)
		if form_msg.is_valid():
			usuario = form_msg.cleaned_data['mensaje']
			autor = str(request.user)

			models.Seguidos.objects.create(seguidor= autor, seguido=str(usuario))
			msg = msg_seguir_usuario(autor, str(usuario))		# LLAMA A PRODUCTOR (PRODUCER.PY)

			print (msg)
			messages.success(request, autor + " sigue a "+ str(usuario))
			form_msg = forms.BuscarUsrForm()
		else:
			form_msg = forms.BuscarUsrForm()
	else:
		form_msg = forms.BuscarUsrForm()
	
	context = {'form_msg': form_msg }

	return render(request, 'buscarUsuarios.html', context)


@login_required(login_url='login')
def notificaciones(request):

	lst_msg_generator_seg_aux = []
	lst_msg_generator_seg = []

	lst_msg_generator_likes_aux = []
	lst_msg_generator_likes = []

	user = str(request.user)

	generator_seguidores = notifiSeguim_lst_msg(user)		# LLAMA A CONSUMIDOR (CONSUMER.PY)
	generator_likes = notifiLikes_lst_msg(user)				# LLAMA A CONSUMIDOR (CONSUMER.PY)

	for item in generator_seguidores:				# EXTRAE CADA MJE DEL TOPIC Y LO GUARDA EN UNA LISTA
		for i in item:
			lst_msg_generator_seg_aux.append(i)				
		
	for item in lst_msg_generator_seg_aux[::-1]:			#INVIERTE EL ORDEN DE LA LISTA PARA QUE EL MJE MAS RECIENTE ESTE PRIMERO
		lst_msg_generator_seg.append(item)
	print (lst_msg_generator_seg)

	for item in generator_likes:				# EXTRAE CADA MJE DEL TOPIC Y LO GUARDA EN UNA LISTA
		for i in item:
			lst_msg_generator_likes_aux.append(i)				
		
	for item in lst_msg_generator_likes_aux[::-1]:			#INVIERTE EL ORDEN DE LA LISTA PARA QUE EL MJE MAS RECIENTE ESTE PRIMERO
		lst_msg_generator_likes.append(item)
	print (lst_msg_generator_likes)


	context = {'item_list_seg': lst_msg_generator_seg, 'item_list_likes': lst_msg_generator_likes}

	return render(request, 'notificaciones.html', context)

template_project/template_app/templates/base.html
{% load static %} 
<html>
 
<head>
	<title>Kafka</title>
	<meta charset="ISO-8859-1">
	<link rel="stylesheet" href="{% static '../template_project/static/css/index.css' %}" />	
	<link rel="shortcut icon" href="{% static '../template_project/static/img/logo.ico' %}" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body class="base">

	<div class="base">

		<ul class="navbar">
			<li><a href="/home">Home</a></li>
			<li><a href="/crearPost">CargarPost</a></li>
			<li><a href="/verNoticias">Noticias</a></li>
			<li><a href="/buscarUsuarios">BuscarUsuarios</a></li>

			<li id="right_navbar"><a href="{% url 'logout' %}"><img class ="icono" src="{% static '../template_project/static/img/logout.png'%}" alt="Salir" title="Salir"> Salir </a></li>
			<p> &#160; Hola {{request.user}} &#160;</p>
			<li id="right_navbar"><a href="/notificaciones"><img class ="icono" src="{% static '../template_project/static/img/notif.png'%}" alt="Salir" title="Salir"> Notificaciones </a></li>
		</ul>

			{% block content %}

			{% endblock %}
	</div>
	
</body>


</html>

template_project/template_app/templates/base_login.html
{% load static %} 
<html>
 
<head>
	<title>Kafka</title>
	<meta charset="ISO-8859-1">
	<link rel="stylesheet" href="{% static '../template_project/static/css/index.css' %}" />	
	<link rel="shortcut icon" href="{% static '../template_project/static/img/logo.ico' %}" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body class="base">

	<div class="base">

			{% block content %}

			{% endblock %}
	</div>
	
</body>


</html>

template_project/template_app/templates/buscarUsuarios.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<!--	50% IZQ - TABLA DE DATOS -->	

	<div class='contenido_form'>
		<p class="titulo">BUSCAR USUARIOS PARA SEGUIR</p>

					<form enctype ="multipart/form-data" method="post">
						{% csrf_token %}

							{{form_msg.mensaje }} &#160;
							<button class="login_form" type="submit">
							<img class ="icono" src="{% static '../template_project/static/img/search.png' %}" alt="Seguir" title="Seguir">  Seguir
							</button>

							{% for message in messages %}
								<p>{{message}}</p>
							{% endfor %}
							
					</form>

			<br>
		</div>
	</div>






{% endblock %}

template_project/template_app/templates/cargaPost.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<!--	50% IZQ - TABLA DE DATOS -->	


	<div class='base'>
		<div class='contenido_form'>
			<p class="titulo">CREAR POST</p>
			<form enctype ="multipart/form-data" method="post">
				{% csrf_token %}
				{{form_post.titulo}}
				<br>
				{{form_post.imagen.label}} {{form_post.imagen}}
				<br>
				{{form_post.texto}}
				<br>
				<br>
				<br>
				<button type="reset" value="Reset">
					<img class ="icono" src="{% static '../template_project/static/img/refresh.png' %}" alt="Reset" title="Reset">  Reset
				</button>
				<button class="login_form" type="submit">
					<img class ="icono" src="{% static '../template_project/static/img/send.png' %}" alt="Cargar" title="Cargar">  Subir
				</button>
				{% for message in messages %}
					<p>[MSG FROM CONTROLLER] {{message}}</p>
				{% endfor %}
			</form>
			<br>
		</div>
	</div>



{% endblock %}

template_project/template_app/templates/home.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<!--	50% IZQ - TABLA DE DATOS -->	


	







{% endblock %}

template_project/template_app/templates/index.html
{% extends "base_login.html" %}
{% load static %} 
{% block content %}


<div class="base">
	
<div class="register_form">
	<form method="post">
		{% csrf_token %}
		<br>
		{{form.username}}
		<br>
		{{form.password}}
		<br>
		{{form.errors}}
		<br>
		<button class="login_form" type="submit">
			<img class ="icono" src="{% static '../template_project/static/img/login.png' %}" alt="Ingresar" title="Ingresar">  Ingresar
		</button>

		{% for message in messages %}
			<p>{{message}}</p>
		{% endfor %}

		<br>
		<p> No tienes una cuenta creada ? <a href ="{% url 'register' %}">registrate</a> </p>

	</form>
</div>
</div>



{% endblock %}

template_project/template_app/templates/notificaciones.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<!--	50% IZQ - TABLA DE DATOS -->	

	<div class='contenido_form'>
		<p class="titulo">LISTA DE MENSAJES EN TOPIC SEGUIDORES DESDE SERVER KAFKA.</p>
		<div class='table_container'>
			<table class="tabla">
				<tr>
					<th>MENSAJE</th>
				</tr>
				{% for item in item_list_seg %}
				<tr>
					<td>{{ item }} </td> 
				</tr>
				{% endfor %}
			</table>
			<br>
		</div>
	</div>

	<div class='contenido_form'>
		<p class="titulo">LISTA DE MENSAJES EN TOPIC LIKES DESDE SERVER KAFKA.</p>
		<div class='table_container'>
			<table class="tabla">
				<tr>
					<th>MENSAJE</th>
				</tr>
				{% for item in item_list_likes %}
				<tr>
					<td>{{ item }} </td> 
				</tr>
				{% endfor %}
			</table>
			<br>
		</div>
	</div>






{% endblock %}

template_project/template_app/templates/register.html
{% extends "base_login.html" %}
{% load static %} 
{% block content %}


<div class="register_form">
	<form method="post">
		{% csrf_token %}
		<br>
		{{form.username}}
		<br>
		{{form.first_name}}
		<br>
		{{form.password1.help_text}}
		{{form.password1}}
		<br>
		{{form.password2}}
		<br>
		<br>
		<br>
		<button type="submit">
			<img class ="icono" src="{% static '../template_project/static/img/login.png'%}" alt="Registrarse" title="Registrarse">  Registrarse
		</button>

		{% for message in messages %}
			<p>{{message}}</p>
		{% endfor %}

		<br>
		<p> Ya tienes una cuenta ? <a href ="{% url 'login' %}">loguea</a> </p>
	</form>
</div>

{% endblock %}

template_project/template_app/templates/verNoticias.html
{% extends "base.html" %}
{% load static %} 
{% block content %}

<!--	50% IZQ - TABLA DE DATOS -->	

	<div class='contenido_form'>
		<p class="titulo">LISTA DE POSTS EN TOPIC NEWS DESDE SERVER KAFKA.</p>

				{% for item in item_list %}
				<div class="post">
					<form method="post">
					{% csrf_token %}

					<h3>{{ item.autor }} publico:</h3>	

					<h1>{{ item.titulo }}</h1>
					<img src="{{item.imagen}}" alt="" width="250" height="100"> </img>
					<p>{{ item.text }}</p>&#160;


					<input type="hidden" name="autor" id="id_autor" value= "{{item.autor}}"> 
					<input type="hidden" name="titulo" id="id_titulo" value="{{item.titulo}}">
					<input type="hidden" name="texto" id="id_texto" value= "{{item.text}}">


					<button class="login_form" type="submit">
					<img class ="icono" src="{% static '../template_project/static/img/like.png' %}" alt="Like" title="Like">  Like
					</button>
					</form>
				</div>
				{% endfor %}

			<br>
	</div>






{% endblock %}